<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VTR22OTJ" failures="1" tests="2" name="Regression" time="8.201" errors="0" timestamp="2023-05-04T14:30:51 IST">
  <testcase classname="pom.tc.LoginTest" name="LoginTestMethod" time="2.855"/>
  <testcase classname="pom.tc.LoginGetItemsTest" name="LoginGetItemsTestMethod" time="2.875">
    <failure type="java.lang.AssertionError" message="expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [6]
at pom.tc.LoginGetItemsTest.LoginGetItemsTestMethod(LoginGetItemsTest.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- LoginGetItemsTestMethod -->
</testsuite> <!-- Regression -->
